name: Bug Report
description: Report a reproducible bug or issue in Aether Calendar
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below as clearly as possible.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Which OS, browser, or version are you using?
      placeholder: ex. Ubuntu 22.04, Chrome 124, Node.js 18.x
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: ex. The inbox page crashes when switching folders quickly.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to Inbox
        2. Click on Folder X
        3. Switch quickly to Folder Y
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste any error messages or include screenshots to help us understand the issue.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have tested the latest version
          required: true
        - label: I have checked for duplicate issues
          required: true
