name: Feature Request
description: Suggest an idea or improvement for Aether Calendar
title: "[Feature]: "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please complete the following form to help us understand your idea.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Give a short title or summary of your idea.
      placeholder: ex. Dark Mode for Webmail

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Describe the feature you'd like to see implemented.
      placeholder: ex. It would be great to have a dark mode toggle that remembers user preference...

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
      description: Explain the value this feature adds to Aether Mail.
      placeholder: ex. Many users work at night and dark mode would reduce eye strain.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Are there any other workarounds or solutions you've tried?
      placeholder: ex. Currently using a browser extension to invert colors...

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have searched for similar feature requests
          required: true
